### ISSUE TITLE
Completed command bug

### ISSUE THREAD

**Issue by guekling** [CS2103JAN2018-W13-B4/main#226]
@dominickenn 

StatusBarFooter is shown as this (this problem also occured in `uncompleted` command):
EDIT: SHIT. Only `list` shows the correct task number. Every other command fails. I think someone broke it? Pretty sure it was working because it was copied for AB4. LOLS.

![screen shot 2018-04-07 at 11 53 24 pm](https://user-images.githubusercontent.com/24616618/38457122-fc9373aa-3abe-11e8-94e8-fe140c102099.png)

Results is shown as this:
![screen shot 2018-04-07 at 11 53 45 pm](https://user-images.githubusercontent.com/24616618/38457126-050352a8-3abf-11e8-8c5e-7bf5ca757cf0.png)

**Comment by dominickenn** [comment]
Previously, in context of AB4, all persons are showed regardless of filter. Once I added the login system, I needed it to be specific to the total tasks a user has, so I changed it a bit. Because it retrieves information straight from the organizer, but not the filteredlist. (OrganizerChangedEvent contains ReadOnlyOrganizer, not ModelManager)

**Comment by dominickenn** [comment]
Or maybe I can set it to say, "x? uncompleted/completed task(s) total"

**Comment by guekling** [comment]
Hmmms... I remembered it having at least `0 task(s) total` last time? Or did I remember wrong? Cos it's just stuck at the total number of tasks right now. I mean, if it still persists, we can always scrap it. LOLS. It was from the v1.1 where we could copy from AB4's github.

I don't think putting `x?` is a good idea. Lols.
